# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: "Build and Test"
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - name: "Run Tests"
        run: ./gradlew test
